export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_COUNTRY_NAME = "GET_COUNTRY_NAME";
export const GET_COUNTRY_ID = "GET_COUNTRY_ID";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const SORT = "SORT";
export const SORT_POPULATION = "SORT_POPULATION";
export const SORT_CONTINENT = "SORT_CONTINENT";
export const SORT_ACTIVITY = "SORT_ACTIVITY";
export const CLEAR_DETAIL = "CLEAR_DETAIL";

// export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
